tap "puma/puma"
tap "homebrew/fuse"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"

brew "aircrack-ng"
brew "axel"
brew "base64"
brew "c2048"
brew "coreutils"
brew "curl"
brew "gdrive"
brew "git"
brew "gnupg"
brew "libtool"
brew "htop"
brew "hub"
brew "lftp"
brew "libyaml"
brew "markdown"
brew "mas"
brew "mplayer"
brew "mplayershell"
brew "mysql"
brew "nmap", link: false
brew "node"
brew "nvm"
brew "openssl@1.1"
brew "pulseaudio", restart_service: true
brew "reattach-to-user-namespace"
brew "shpotify"
brew "sqlite"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tmux"
brew "tree"
brew "utf8proc"
brew "v8"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"

cask "airdroid"
cask "alfred"
cask "battle-net"
cask "bettertouchtool"
cask "calibre"
cask "cgoban"
cask "deluge"
cask "discord"
cask "dropbox"
cask "eqmac"
cask "flirc"
cask "flux"
cask "gimp"
cask "google-chrome"
cask "google-hangouts"
cask "inboxer"
cask "iterm2"
cask "lacona"
cask "mactex"
cask "mplayer-osx-extended"
cask "mplayerx"
cask "muzzle"
cask "onedrive"
cask "skype"
cask "slack"
cask "spotify"
cask "steam"
cask "vlc"
cask "whatsapp"
cask "zotero"

mas "Colors", id: 581915465
mas "iLightShow", id: 1217138942
mas "Simple Recorder", id: 989175722
