#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# update cache
sudo pacman -Sy
# install things in aptfile
echo "install things in pkglist.txt"
sudo pacman -S - < pkglist.txt
# install personnal binaries
echo "install personnal binaries"
ln -s ~/dotfiles/install/bin ~/bin
# find the installers and run them iteratively
echo "find the installers and run them iteratively"
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
# install oh-my-zsh
echo "install oh-my-zsh"
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
# add some custom plugins
echo "add some custom plugins"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
